In [ ]:
# create array with np.array([list]) function

import numpy as np

ar1 = np.array(list("12345"))
ar1

In [32]:
# ar init to zeros

ar2 = np.zeros((3,4))
ar2


array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [35]:
# ar init to 1s
ar3 = np.ones((2,3))
ar3

array([[1., 1., 1.],
       [1., 1., 1.]])

In [43]:
# ar init to any 1s but int type ( any array can take argument dtype)
ar4 = np.ones((2,3), dtype=np.int)
#ar4 = np.ones((2,3), dtype=np.str)
#ar4 = np.zeros((2,3), dtype=float)
ar4

array([[1, 1, 1],
       [1, 1, 1]])

In [71]:
# ar with eye along diagonal
ar5 = np.eye(3, dtype=np.int16)
ar5

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]], dtype=int16)

In [83]:
# ar with range and step
# can take one arg, starts with zero and steps by 1 at a time
ar6 = np.arange(2,20,4)
print(ar6)

print(np.arange(0,20,1).reshape(5,4))

[ 2  6 10 14 18]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]


In [73]:
# ar 2d - takes a list of two lists
ar6 = np.array([(1,3,4), (8,8,9)])
ar6

array([[1, 3, 4],
       [8, 8, 9]])

In [74]:
# show array shape
np.shape(ar6)

(2, 3)

In [75]:
#practice - create array and then reshape it
ar7 = np.zeros((2,3), dtype=np.int16).reshape(3,2)
ar7


array([[0, 0],
       [0, 0],
       [0, 0]], dtype=int16)

In [79]:
# create similar array
ar8 = np.ones_like(ar7)
ar8

array([[1, 1],
       [1, 1],
       [1, 1]], dtype=int16)

In [98]:
# control printing options
# to print everything
import sys

np.set_printoptions(threshold=sys.maxsize)
ar100 = np.arange(40).reshape(4,10)
ar100

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])

In [124]:
#### array opertions #####  =, -, *, %, /, >, < 

a = np.arange(1,5).reshape(2,2)
b = np.ones((2,2), dtype=np.int16)
b=b*5

print(a+10) # to all gives new array
print(a+b)
print(a*b) # This is NOT matrix multiplication
print(a/b)
print(a>3) 
print(a.dot(b)) # this IS matrix multiplication

[[11 12]
 [13 14]]
[[6 7]
 [8 9]]
[[ 5 10]
 [15 20]]
[[0.2 0.4]
 [0.6 0.8]]
[[False False]
 [False  True]]
[[15 15]
 [35 35]]


In [147]:
# regular stats function

print(a)
print(a.max(),a.min(),a.mean(), a.sum())


[[1 2]
 [3 4]]
4 1 2.5 10


In [148]:
## axis = 0 - columns
## axis = 1 - rows
# ! - anything can take axis arugment to flip the rows to columns of columns to rows

print(a.sum(axis=1))
print(a.sum(axis=1)) # sum along the rows
print(a.sum(axis=0)) # sum along the columns

[3 7]
[3 7]
[4 6]


In [192]:
## reading input from a file in nympy #### np.getfromtxt(takes, list of columns, delimi, data types, names)

file=r'D:\dev\large_dataset\numpy_sample.csv'
types = ['f8', 'f8', 'U50', 'i4', 'i4', 'i4', 'i4', 'i4']
ba = np.genfromtxt(file,      delimiter=',', dtype=types,   names=True)

array([( 982903.5699382 , 205129.99858244, '1 7 AV S',  5, 0, 0, 0,  5),
       ( 987330.41607136, 191302.73030527, '1 BOERUM PL',  1, 0, 0, 0,  1),
       ( 983210.9531817 , 199016.5134341 , '1 CENTRE ST', 10, 0, 0, 0, 10),
       ( 985897.8395402 , 207157.88527469, '1 E 13 ST',  1, 0, 0, 0,  1),
       (1010993.96946594, 252137.33960694, '1 E 183 ST',  0, 0, 2, 0,  2),
       ( 987774.37089211, 210586.44665901, '1 E 28 ST',  1, 0, 0, 0,  1)],
      dtype=[('X', '<f8'), ('Y', '<f8'), ('Name', '<U50'), ('small', '<i4'), ('large', '<i4'), ('circular', '<i4'), ('mini_hoop', '<i4'), ('total_rack', '<i4')])

In [221]:
ar= np.arange(20).reshape(4,5)
ar

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [224]:
# array index accessing is with ar[row range, column range]
# row range will be in 1:2 format and column range is in 3:4 format
ar[:,:]

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [228]:
# flatten - flattens the array - order = F makes it go for column major form
# similar function called np.nditer
for i in ar.flatten( order = 'F'):
    print(i)

0
5
10
15
1
6
11
16
2
7
12
17
3
8
13
18
4
9
14
19


In [241]:
#split - splits arrays by index

# create a views on numpy array with view function

arv = ar.view() # Here arv is shallow copy, meaning different objects

print(arv is ar)

False


In [239]:
#Deep copy - making a full copy of an array
#Changes will not reflect in the original copy

In [250]:
## structured array

strd = np.zeros(4, dtype={'names':('a', 'b', 'c'), 'formats': ('str', 'str', 'str')})
strd


array([('', '', ''), ('', '', ''), ('', '', ''), ('', '', '')],
      dtype=[('a', '<U'), ('b', '<U'), ('c', '<U')])

In [255]:
"""
Broadcasting - to work with arrays with mismatched shape
e.g if I am multiplying with 10 to ar then steps:
create array for 10 with dimentions of the arr to be multiplied to
Then do the multiplication and the result is broadcasted full array.
This is example of scalar broadcasting.

Same if the concept of broadcasting of arrays.
Only smaller shape array can be broadcasted on smaller

"""

ar * 10 # first there was an array that was created of same shape as ar filled with 10 and them it was multiplied

array([[  0,  10,  20,  30,  40],
       [ 50,  60,  70,  80,  90],
       [100, 110, 120, 130, 140],
       [150, 160, 170, 180, 190]])

In [260]:
## array broadcasting ####

a1 = np.arange(10).reshape(2,5)
a2 = np.arange(4).reshape(2,2)

print(a1,a2)


[[0 1 2 3 4]
 [5 6 7 8 9]] [[0 1]
 [2 3]]


In [277]:
#pandas

import pandas as pd

data = pd.read_csv(r'D:\dev\large_dataset\titanic.csv')
data.head()



PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [278]:
# drop function - to drop the column 

data.drop(columns='Cabin')

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Embarked  
0        0         A/5 21171   7.2500        S  
1        0          PC 17599  71.2833        C  
2        0  STON/O2. 3101282   7.9250        S  
3        0            113803  53.1000        S  
4        0            373450   8.0500        S  
..     ...               ...      ...      ...  
886      0            211536  13.0000        S  
887      0            112053  30.0000        S  
888      2        W./C. 6607  23.4500        S  
889      0            111369  30.0000        C  
890      0            370376   7.7500        Q  

[891 rows x 11 columns]

In [275]:
# isNa function - T or F if the value is not available
np.sum(data['Age'].isna()) 

177

In [291]:
# aggrerate
agr = data.groupby('Embarked').aggregate(np.mean)
agr

PassengerId  Survived    Pclass        Age     SibSp     Parch  \
Embarked                                                                   
C          445.357143  0.553571  1.886905  30.814769  0.386905  0.363095   
Q          417.896104  0.389610  2.909091  28.089286  0.428571  0.168831   
S          449.527950  0.336957  2.350932  29.445397  0.571429  0.413043   

               Fare  
Embarked             
C         59.954144  
Q         13.276030  
S         27.079812

In [295]:
agr[['Age', 'Fare']]

Age       Fare
Embarked                      
C         30.814769  59.954144
Q         28.089286  13.276030
S         29.445397  27.079812

In [306]:
total = np.count_nonzero(data['PassengerId'])
survived = np.count_nonzero(data['Survived'])
p = (survided / total) * 100

In [309]:
print("Total = %i" %total)
print("Survived = %i" %survived)
print("Percentage = %i" %p)

Total = 891
Survived = 342
Percentage = 38


In [328]:
female = data[data['Sex'] == 'female']
survived_female = np.count_nonzero(female['Survived'])
print("Females survived %i" %survived_female)

Females survived 233


In [332]:
male = data[data['Sex'] == 'male']
survived_male = np.count_nonzero(male['Survived'])
print("Males survived %i" %survived_male)

Males survived 109


In [337]:
class_bd = data.groupby('Pclass').aggregate(np.count_nonzero)
class_bd

PassengerId  Survived  Name  Sex    Age  SibSp  Parch  Ticket   Fare  \
Pclass                                                                         
1               216       136   216  216  216.0     79     53     216  211.0   
2               184        87   184  184  184.0     64     50     184  178.0   
3               491       119   491  491  491.0    140    110     491  487.0   

        Cabin  Embarked  
Pclass                   
1         216       216  
2         184       184  
3         491       491

In [341]:
class_bd[['Survived']]

Survived
Pclass          
1            136
2             87
3            119

In [350]:
# vectorize - function turns s regular method into a method that can be called on a multi dimensional array
# create a simple function and use it on numpy arrays is called vectorization
# 

import numpy as np

def sum(a,b):
    return (a+b)

na = np.arange(10).reshape(2,5)
vec = np.vectorize(sum) 

print(vec(na[0],na[1]))

[ 5  7  9 11 13]
