In [2]:
import numpy as np

#create array with a list
ar1 = np.array([1,2,3,4, "five"]) # this can be heterogeneous
print(ar1)

['1' '2' '3' '4' 'five']


In [4]:
# create array with a list in a arr variable
nums = [1,2,2,3]
ar2 = np.array(nums)

In [5]:
ar2

array([1, 2, 2, 3])

In [6]:
# init array with zeros
ar_zero = np.zeros((3,3))
ar_zero

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [7]:
# init array with 1s for int16s
ar1s = np.ones((3,3), dtype=np.int16)
ar1s

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]], dtype=int16)

In [9]:
# empty array without initilization
arempty = np.empty((3,3))
arempty

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [12]:
# eye arrat
areye = np.eye(3,3)
areye

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [14]:
# arange function sets up range of values
# takes steps as argument
# start, end, range
arange = np.arange(1, 10, 2)
arange

array([1, 3, 5, 7, 9])

In [15]:
#arange float by setting step size of floating point
arange_float = np.arange(1,10,0.9)
arange_float

array([1. , 1.9, 2.8, 3.7, 4.6, 5.5, 6.4, 7.3, 8.2, 9.1])

In [19]:
#2d arrays
ar2d = np.array([(1,2,3), (3,4,5)])
ar2d

array([[1, 2, 3],
       [3, 4, 5]])

In [27]:
# Shaping arrays
# Every numpy array has a shape
# usual practice is to create an array and then shape it. e.g.

arshape = np.arange(6) # this one only declared 
arshape = np.arange(6).reshape(3,2) # reshaped it in 3,2 matrix
# matrix elements should match
arshape

array([[0, 1],
       [2, 3],
       [4, 5]])

In [29]:
#Create an array of same shape with ones_like method and init them with 1
arlike = np.ones_like(arshape)
arlike

array([[1, 1],
       [1, 1],
       [1, 1]])

In [31]:
## Printing arrays ###

ar1 = np.arange(6)

In [41]:
b = np.arange(12).reshape(2,2,3)
b

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [61]:
#the number of square brackets shows if the array is 2 or 3 or 4 dimensional
ar100 = np.arange(100).reshape(10,10)

In [63]:
#To print all the arrays without lmiting the it will ..
#you can configure the printing display with set_printoptions(). This takes threshold as an arugment. This does not allow 
#value np.nan. If you set it to max of what system allows then everythign will be printed.
import sys
np.set_printoptions(threshold=sys.maxsize)
ar100



array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [85]:
### Basic array operations ####
#adding, subtracting, multiplication, division  arrays - This adds the elements in the array one by one.
# the array shape must be identical


a = np.array([10,10,10])
b = np.array([5,5,5])
a+b

array([15, 15, 15])

In [81]:
a-b

array([5, 5, 5])

In [82]:
a*b

array([50, 50, 50])

In [89]:
a/b

array([2., 2., 2.])

In [91]:
# This works with regular math values e.g.
a/2 # produces 5

array([5., 5., 5.])

In [92]:
a % 3

array([1, 1, 1], dtype=int32)

In [94]:
# conditional operator this renders boolean array
a < 2

array([False, False, False])

In [106]:
# metrix multiplication uses dot operator
a.dot(b)

150

In [145]:
#matrix multiplication for 2d arrays
a2d = np.arange(4).reshape(2,2)
b2d = np.arange(4).reshape(2,2)

In [146]:
print(f"A:\n{a2d}\n",f"B:\n{b2d}\n")

A:
[[0 1]
 [2 3]]
 B:
[[0 1]
 [2 3]]



In [147]:
#Metrix multiplication = [row,col] = sum(all elements in the row * all elements in the col)
print(np.dot(a2d,b2d)) # Notice multiplication result in 2x2 metrix

[[ 2  3]
 [ 6 11]]


In [149]:
# alternate syntax
a2d.dot(b2d)

array([[ 2,  3],
       [ 6, 11]])

In [150]:
b2d = a2d + 2
a2d

array([[0, 1],
       [2, 3]])

In [142]:
ar1 = np.arange(4)
ar1

array([0, 1, 2, 3])

In [143]:
ar1 *= 3
ar1

array([0, 3, 6, 9])

In [152]:
print(ar1.max()) # other operator max, min, sum, # works the same on two dimentional arrays

print(a2d)
print(a2d.max())

9
[[0 1]
 [2 3]]
3


In [154]:
# applying operations on particular axis of the matrix 0 - rows and 1- columns, This applies to sum, min, max etc.
ar23 = np.arange(6).reshape(2,3)
ar23

array([[0, 1, 2],
       [3, 4, 5]])

In [155]:
# using axis argument 
ar23.sum(axis=0) # sums up all the elements along all the columns

array([3, 5, 7])

In [157]:
ar23.sum(axis=1) # sums up all the elements along all the rows

array([ 3, 12])

In [164]:
# trignometry functions are available as builtins
print("Pi is available as builtin", np.pi)

Pi is available as builtin 3.141592653589793


In [165]:
print("Radians >", np.radians(90), " Sin > ", np.sin(90), " Cos > ", np.cos(90))

Radians > 1.5707963267948966  Sin >  0.8939966636005579  Cos >  -0.4480736161291701


In [182]:
# other stats fucntionare available as builtin e.g.
scores = np.arange(10).reshape(5,2)
print("Mean ", scores.mean(), " OR ", np.mean(scores))
print("Median ", np.median(scores))


Mean  4.5  OR  4.5
Median  4.5


In [191]:
#### Loading data from csv #######
salaries = np.genfromtxt('D:/dev/large_dataset/ml-20m/links.csv', delimiter=',')
salaries

array([[          nan,           nan,           nan],
       [1.0000000e+00, 1.1470900e+05, 8.6211000e+02],
       [2.0000000e+00, 1.1349700e+05, 8.8441100e+03],
       [3.0000000e+00, 1.1322800e+05, 1.5602110e+04],
       [4.0000000e+00, 1.1488500e+05, 3.1357110e+04],
       [5.0000000e+00, 1.1304100e+05, 1.1862110e+04],
       [6.0000000e+00, 1.1327700e+05, 9.4911000e+02],
       [7.0000000e+00, 1.1431900e+05, 1.1860110e+04],
       [8.0000000e+00, 1.1230200e+05, 4.5325110e+04],
       [9.0000000e+00, 1.1457600e+05, 9.0911100e+03],
       [1.0000000e+01, 1.1318900e+05, 7.1011000e+02],
       [1.1000000e+01, 1.1234600e+05, 9.0871100e+03],
       [1.2000000e+01, 1.1289600e+05, 1.2110110e+04],
       [1.3000000e+01, 1.1245300e+05, 2.1032110e+04],
       [1.4000000e+01, 1.1398700e+05, 1.0858110e+04],
       [1.5000000e+01, 1.1276000e+05, 1.4081100e+03],
       [1.6000000e+01, 1.1264100e+05, 5.2411000e+02],
       [1.7000000e+01, 1.1438800e+05, 4.5841100e+03],
       [1.8000000e+01, 1.131

In [195]:
#exploring data, mean, median, standard deviation and variance are the common function available

In [273]:
#### Indexing and slicing ####

# indexing is same as how it's in the python list
ari = np.arange(11)**2
ari

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100], dtype=int32)

In [275]:
print("One > ", ari[2], "Two > ", ari[2:-1])
print("Stepping ->", ari[1:8:2]) # accessed index alternate of 2, startring with 1

#reversing array with indices. Step = -1, means stepping backwards
print(ari[::-1]) #This has revervsed the arrays

One >  4 Two >  [ 4  9 16 25 36 49 64 81]
Stepping -> [ 1  9 25 49]
[100  81  64  49  36  25  16   9   4   1   0]


In [276]:
ar2d = np.arange(15).reshape(5,3)
print(ar2d, "\n", ar2d[0],"\n") #for a 2d array the first row is accesible with row,column method. So ar2d[0] will print the whole row
print(ar2d[0,2],"\n") # accessing specific element with row.column

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]] 
 [0 1 2] 

2 



In [234]:
#specifiying range for rows and columns
ar2d[0:2, 1:2] # is 0:2 rows and 2:4 range for columns 

array([[1],
       [4]])

In [277]:
ar2d[:,1:3] # all the rows but 1:3 range for columns

array([[ 1,  2],
       [ 4,  5],
       [ 7,  8],
       [10, 11],
       [13, 14]])

In [278]:
# negative index for multi dimensional arrays
ar2d[-1:,:-1]

array([[12, 13]])

In [279]:
## iterating over 2d+ arrays
# This iterates through every number in the matrix
for i in ar2d:
    print(i)

[0 1 2]
[3 4 5]
[6 7 8]
[ 9 10 11]
[12 13 14]


In [280]:
# using flatten function you get every element in the array one by one
# it takes argument order, possible values = F - columnar printing, column1, 2, 3 etc.
# returns the results of the flattened list
for i in ar2d.flatten(order='F'):
    print(i)

0
3
6
9
12
1
4
7
10
13
2
5
8
11
14


In [248]:
#iterating with nditer - this iterated in row major form again. order=F can be used to column major
# does not retuen anything, just allwos you to interate through
for i in np.nditer(ar2d):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14


In [281]:
print(ar2d)
# using nditer to get inner most loop ???? This has created transpose of the matrix
for i in np.nditer(ar2d, order='F', flags = ['external_loop']):
    print(i)
    
print(ar2d)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]
[ 0  3  6  9 12]
[ 1  4  7 10 13]
[ 2  5  8 11 14]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


In [291]:
#nd iter in readwrite mode
for i in np.nditer(ar2d):
    print(i)

ar2d

# updating 2d array in place
for i in np.nditer(ar2d, op_flags=['readwrite']):
    i[...] = i * i 

ar2d

0
1
16
81
256
625
1296
2401
4096
6561
10000
14641
20736
28561
38416


array([[         0,          1,        256],
       [      6561,      65536,     390625],
       [   1679616,    5764801,   16777216],
       [  43046721,  100000000,  214358881],
       [ 429981696,  815730721, 1475789056]])

In [381]:
## Changing shape of the array

a = np.array(
    [
        list("here I am".split()),
        list("here U are".split()),
        list("here Y are".split()),
        list("here D are".split()),
        list("here H are".split()),
        list("here X are".split())
    ]
)

print(a)
a.ravel()

[['here' 'I' 'am']
 ['here' 'U' 'are']
 ['here' 'Y' 'are']
 ['here' 'D' 'are']
 ['here' 'H' 'are']
 ['here' 'X' 'are']]


array(['here', 'I', 'am', 'here', 'U', 'are', 'here', 'Y', 'are', 'here',
       'D', 'are', 'here', 'H', 'are', 'here', 'X', 'are'], dtype='<U4')

In [382]:
# transpose of the array with T. Thats all
a.T

array([['here', 'here', 'here', 'here', 'here', 'here'],
       ['I', 'U', 'Y', 'D', 'H', 'X'],
       ['am', 'are', 'are', 'are', 'are', 'are']], dtype='<U4')

In [383]:
a.T.ravel()

array(['here', 'here', 'here', 'here', 'here', 'here', 'I', 'U', 'Y', 'D',
       'H', 'X', 'am', 'are', 'are', 'are', 'are', 'are'], dtype='<U4')

In [384]:
# Shape function gives the dimension of the array
a.shape

(6, 3)

In [385]:
# reshape with -1. -1 means that we do not now the value of the dimension is. So Numpy will create as many rows to fit the data
print(a.reshape(-1,3))


[['here' 'I' 'am']
 ['here' 'U' 'are']
 ['here' 'Y' 'are']
 ['here' 'D' 'are']
 ['here' 'H' 'are']
 ['here' 'X' 'are']]


In [386]:
# split array - There is split is vertical split
# hsplit is horizontal split
print(np.split(a,2))

[array([['here', 'I', 'am'],
       ['here', 'U', 'are'],
       ['here', 'Y', 'are']], dtype='<U4'), array([['here', 'D', 'are'],
       ['here', 'H', 'are'],
       ['here', 'X', 'are']], dtype='<U4')]


In [387]:
# hsplit is horizontal split
p1, p2, p3 = np.hsplit(a,3)
print(p1,p2,p3)

[['here']
 ['here']
 ['here']
 ['here']
 ['here']
 ['here']] [['I']
 ['U']
 ['Y']
 ['D']
 ['H']
 ['X']] [['am']
 ['are']
 ['are']
 ['are']
 ['are']
 ['are']]


In [388]:
# Views 
# you can make a view over an array
# view() - creates the shallow copies of the array

In [389]:
a1 = a.view()
a2 = a.view()
print(id(a1), id(a2), id(a))

209081912 209083112 186605960


In [391]:
print(a1)
a1[0]='XX'

[['here' 'I' 'am']
 ['here' 'U' 'are']
 ['here' 'Y' 'are']
 ['here' 'D' 'are']
 ['here' 'H' 'are']
 ['here' 'X' 'are']]


In [392]:
a1

array([['XX', 'XX', 'XX'],
       ['here', 'U', 'are'],
       ['here', 'Y', 'are'],
       ['here', 'D', 'are'],
       ['here', 'H', 'are'],
       ['here', 'X', 'are']], dtype='<U4')

In [397]:
# Deep copies of an array
acopy = a.copy()
print(acopy)

[['XX' 'XX' 'XX']
 ['here' 'U' 'are']
 ['here' 'Y' 'are']
 ['here' 'D' 'are']
 ['here' 'H' 'are']
 ['here' 'X' 'are']]


In [401]:
#### indices. numpy allows to use array as index
ilist = [1,2,3]
a[ilist]

array([['here', 'U', 'are'],
       ['here', 'Y', 'are'],
       ['here', 'D', 'are']], dtype='<U4')

In [412]:
# accessing indices in readwrite mode
a[2,2]=77777
print(a)

[['XX' 'XX' 'XX']
 ['here' 'U' 'are']
 ['here' 'Y' '7777']
 ['here' 'D' 'are']
 ['here' 'H' 'are']
 ['here' 'X' 'are']]


In [415]:
#Broadcasting - how numpy treats arrays while working on arrays
arp = np.array([1,1,1,1,1,1])
arp * 10

array([10, 10, 10, 10, 10, 10])

In [420]:
arp.reshape(1,-1,3)

array([[[1, 1, 1],
        [1, 1, 1]]])